# Site settings
title: Sebastián Romero
email: sebastianromerog@gmail.com

twitter_username: sebastianromero
github_username:  sebastianromero

# Build settings
markdown: kramdown
highlighter: rouge

paginate: 3
permalink: '/:title'
sass:
    style: :compressed
